name: deploy-api-to-test

on:
  push:
    branches: ["test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run Prisma Deploy
        uses: borales/actions-yarn@v2.0.0

        with:
          cmd: prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_TEST }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
